name: Test 🧪

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'test-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  functionality:
    name: Functionality ⚙️
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', 3.11, 3.12]
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Setup python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip packages
      uses: ./
      with:
        packages: |
          pip-install-test

    - name: Check if package is installed
      run: python -c 'import pip_install_test'

  code:
    name: Code 👩‍💻
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 19, 20]
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Install node ${{ matrix.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Upload JUnit test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: |
        (success() || failure()) &&
          matrix.os == 'ubuntu-latest' &&
          matrix.node-version == '20'
      with:
        name: test-results
        path: jest-junit.xml

    - name: Publish Test Report
      uses: dorny/test-reporter@d61b558e8df85cb60d09ca3e5b09653b4477cea7 # v1
      if: |
        (success() || failure()) &&
          matrix.os == 'ubuntu-latest' &&
          matrix.node-version == '20'
      with:
        name: JEST Tests
        path: junit.xml
        reporter: jest-junit

    - name: Publish Coverage Report
      if: |
        (success() || failure()) &&
          matrix.os == 'ubuntu-latest' &&
          matrix.node-version == '20'
      uses: ArtiomTr/jest-coverage-report-action@7f750dd50f5585533321eb7ebc482b936b49a5d4 # v2
      with:
        test-script: npm run coverage
